language: python
python:
    - "3.4"
    - "3.3"
    - "3.2"
    - "2.7"

env:
    global:
        - PIP_DOWNLOAD_CACHE=$HOME/.pip-cache
    sudo: false
    cache:
        - $HOME/.pip-cache
    install:
        - pip install tox
    script: tox
